android/urls.py
from django.urls import path
from android import views


app_name = 'android'

urlpatterns = [
    path('', views.AndroidListView.as_view(), name='android-home'),
    path('<int:pk>/', views.android_detail, name='android-detail'),
   #path('tag/<slug:tag_slug>/', views.article_list_by_category, name='article_list_by_tag'),
    path('comment/reply/', views.reply_page, name='reply'),
]

blog/urls.py
from django.urls import path

from blog import views
from blog.feeds import LatestPostsFeed

app_name = 'blog'
urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list_by_category, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name="post_share"),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
    path('about/', views.about, name='about'),
    path('about_site/', views.about_site, name='about_site'),
    path('book_list/', views.BookListView.as_view(), name='book_list'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('<slug:category_slug>/', views.post_list_by_category, name='post_list_by_category'),
    path('<int:pk>/download_image/', views.download_idea_picture, name='download_book_image'),
    path('comment/reply/', views.reply, name='reply'),
]

code_planete/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('java/', include('java.urls', namespace='java')),
    path('android/', include('android.urls', namespace='android')),
    path('pythonbasic/', include('pythonbasic.urls', namespace='pythonbasic')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

java/urls.py
from django.urls import path
from java import views


app_name = 'java'

urlpatterns = [
    #path('', views.JavaListView.as_view(), name='java-home'),
    path('', views.post_list, name='java-home'),
    path('<int:pk>/', views.java_detail, name='java-detail'),
    path('comment/reply/', views.reply_page, name='reply'),
]

pythonbasic/urls.py
from django.urls import path
from pythonbasic import views


app_name = 'pythonbasic'

urlpatterns = [
    path('', views.PythonListView.as_view(), name='home'),
    path('<int:pk>/', views.article_detail, name='article-detail'),
    path('comment/reply/', views.reply_page, name='reply'),
]

blog/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:post_list_by_category', args=[self.slug])


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='posts')
    titre = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = RichTextUploadingField(blank=True, null=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    image = models.ImageField(upload_to='img/', blank=True)
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish', )

    def __str__(self):
        return self.titre

    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.publish.year, self.publish.month,
                                                 self.publish.day, self.slug])

    def get_comments(self):
        return self.comments.filter(parent=None).filter(active=True)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    parent = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True)
    body = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

    def get_comments(self):
        return Comment.objects.filter(parent=self).filter(active=True)


class Book(models.Model):
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    image = models.ImageField(upload_to='img/', blank=True, null=True)
    pdf = models.FileField(upload_to='pdf_file/', blank=True, max_length=250)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return f'{self.title}  - {self.author}'


class Subscribe(models.Model):
    email = models.EmailField()

    def __str__(self):
        return f'{self.email}'

blog/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms

from blog.models import Comment, Subscribe


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25, widget=forms.TextInput(attrs={'class': 'name'}), label='name')
    email = forms.EmailField(label='Email')
    to = forms.EmailField(label='Email')
    comments = forms.CharField(required=False,
                              widget=forms.Textarea, label='Comment')


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')
        widgets = {
            'name':forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Votre nom'}),
            'email':forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Votre email'}),
            'body':forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Commentaire ...'}),
        }


class SearchForm(forms.Form):
    query = forms.CharField()


class SubscribeForm(forms.ModelForm):
    class Meta:
        model = Subscribe
        fields = '__all__'

blog/views.py
import os.path
import datetime
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.core.mail import send_mail
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count, Q
from django.http import FileResponse, HttpResponseNotFound
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.text import slugify
from django.views.generic import ListView
from blog.forms import EmailPostForm, CommentForm, SearchForm, SubscribeForm
from blog.models import Post, Comment, Category, Book
from taggit.models import Tag
from blog.documents import PostDocument, CategoryDocument


def post_list(request, tag_slug=None, category_slug=None):
    now = datetime.datetime.now
    object_list = Post.published.all()
    tag = None
    category = None
    categories = Category.objects.all()

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        object_list = object_list.filter(category__in=[category])
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 6)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first in each page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver the first page
        posts = paginator.page(paginator.num_pages)
    context = {
        'posts': posts,
        'page': page,
        'tag': tag,
        'category': category,
        'categories': categories,
        'now': now,
    }
    return render(request, 'blog/posts/list.html', context=context)


def post_list_by_category(request, category_slug=None, tag_slug=None):
    now = datetime.datetime.now
    object_list = Post.published.all()
    categories = Category.objects.all()
    category = None
    tag = None
    author = None
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        object_list = object_list.filter(category__in=[category])

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 6)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    context = {
        'categories': categories,
        'category': category,
        'posts': posts,
        'page': page,
        'tag': tag,
        'author': author,
        'now': now,
    }
    return render(request, 'blog/posts/post_list_category.html', context=context)


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published', publish__year=year,
                             publish__month=month, publish__day=day)
    categories = Category.objects.all()
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            return redirect(post.get_absolute_url()+'#'+str(new_comment.id))
    else:
        comment_form = CommentForm()
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:2]
    context = {
        'post': post,
        'comments': comments,
        'comment_form': comment_form,
        'similar_posts': similar_posts,
        'categories': categories,
    }
    return render(request, 'blog/posts/detail.html', context=context)


def reply(request):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            post_id = request.POST.get('post_id')
            parent_id = request.POST.get('parent')
            post_url = request.POST.get('post_url')

            reply = form.save(commit=False)
            reply.post = Post(id=post_id)
            reply.parent = Comment(id=parent_id)
            reply.save()
            return redirect(post_url+'#'+str(reply.id))
    return redirect('/')


def post_share(request, post_id):
    # Recuperer un post par son identifiant
    post = get_object_or_404(Post, id=post_id, status='published')
    categories = Category.objects.all()
    sent = False
    if request.method == 'POST':
        # Formulaire a ete soumis
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # formulaire est valide
            cd = form.cleaned_data
            # email envoyé
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommands you read"\
                        f"{post.titre}"
            message = f"Read {post.titre} at {post_url}\n\n"\
                    f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'diarra.msa1@gmail.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    # La liste des posts similaires
    context = {
        'post': post,
        'form': form,
        'sent': sent,
        'categories': categories,
    }
    return render(request, 'blog/posts/share.html', context=context)


def post_search(request, tag_slug=None):
    categories = Category.objects.all()
    object_list = Post.published.all()
    form = SearchForm()
    query = request.GET.get('query')
    tag = None
    results = []
    paginator = Paginator(object_list, 6)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    if query:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.published.filter(Q(titre__icontains=query) | Q(body__icontains=query))
    context = {
        'form': form,
        'query': query,
        'results': results,
        'categories': categories,
        'tag': tag,
        'object_list': object_list,
        'posts': posts,
        'page': page,
    }
    return render(request, 'blog/posts/search.html', context=context)


def about(request):
    categories = Category.objects.all()
    context = {
        'categories': categories
    }
    return render(request, 'blog/posts/about.html', context=context)


def about_site(request):
    categories = Category.objects.all()
    context = {
        'categories': categories
    }
    return render(request, 'blog/posts/about_site.html', context=context)


class BookListView(ListView):
    
    model = Book
    template_name = 'blog/posts/book_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categories = Category.objects.all()
        context['categories'] = categories
        return context


def download_idea_picture(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if book.pdf:
        filename, extension = os.path.splitext(book.pdf.file.name)
        extension = extension[1:]
        response = FileResponse(
            book.pdf.file, content_type=f"image/{extension}"
        )
        slug = slugify(book.title)[:100]
        response["Content-Disposition"] = (
            "attachement; filename="
            f"{slug}.{extension}"
        )
    else:
        response = HttpResponseNotFound(
            content="file invalide"
        )
    return response


def subscribe(request):
    my_form = SubscribeForm()
    if request.method == 'POST':
        my_form = SubscribeForm(data=request.POST or None)
        if my_form.is_valid():
            cd = my_form.cleaned_data
            my_form.save()
            return redirect('blog:book_list')
        else:
            my_form = SubscribeForm()
    else:
        my_form = SubscribeForm()
    return render(request, 'blog/posts/subscribe_email.html', {'my_form': my_form})

blog/templates/blog/posts/comment.html
{% load crispy_forms_tags %}
<div class="border-0 border-start border-2 border-info ps-2" id="{{comment.id}}">
    <div class="mt-3">
        <strong>{{comment.name}}</strong> 
        {% if  comment.parent.name%} to <strong>{{comment.parent.name}}</strong>{% endif %}
        <small class="text-muted">On {{ comment.created.date }}</small>
    </div>
    <div class="border p-2 rounded">
        <p>{{ comment.body|safe }}</p>
        <button class="btn btn-primary btn-sm" onclick="handleReply({{comment.id}})">Reply</button>
    
        <div id="reply-form-container-{{comment.id}}" style="display:none">
        
            <form method="POST" action="{% url 'blog:reply' %}" class="mt-3">
                {% csrf_token %}
                <input type="hidden" name="post_id" value="{{post.id}}">
                <input type="hidden" name="parent" value="{{comment.id}}">
                <input type="hidden" name="post_url" value="{{ post.get_absolute_url }}">
                {{comment_form|crispy }}
                <div class="mt-2">
                    <button type="button" onclick="handleCancel({{comment.id}})" class="btn btn-light border btn-sm">Cancel</button>
                    <button type="submit" class="btn btn-primary btn-sm">Submit</button>
                </div>
            </form>
        </div>
    </div>
    {% for comment in comment.get_comments %}
        {% include 'blog/posts/comment.html' with comment=comment %}
    {% endfor %}
</div>

blog/templates/blog/posts/latest_posts.html
<ul class="list-unstyled">
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.titre }}</a>
        </li>
    {% endfor %}
</ul>

blog/templates/blog/posts/list.html
{% extends 'blog/base.html' %}
{% load static %}
{% load blog_tags %}

{% block content %}


<!-- main -->
<section id="main" class="hero py-5 d-flex align-items-center">
    <div class="container-fluid">
        <div class="row gy-4 align-items-center justify-content-center">
            <a href="{% url 'blog:post_list' %}">
            <div id="carousel_id" class="col col-md-12 col-lg-12 text-white text-center">
                <h2 class="fw-bold p-3 text-white" data-aos="fade-up" ata-aos-delay="400">Vous voulez devenir programmeur informatique ?</h2>
                <div data-aos="fade-up" data-aos-delay="600" class="col col-md-12">
                     <a href="{% url 'blog:post_list' %}" class="btn btn-get-started px-5 py-2 text-uppercase d-inline-flex align-items-center justify-content-center align-self-center">
                         <span class="p-4 mt-1 text-uppercase ">Commencer ici</span>
                     </a>
                </div>
            </div>
            </a>
        </div>
    </div>
</section>


<!-- Section card -->
<section id="pricing" class="pricing">
    <div class="container-fluid" data-aos="fade-up">
        <div class="row gy-4 gy-md-0  gy-lg-4 mt-1justify-content-center" data-aos="fade-left">
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4" data-aos="zoom-in" data-aos-delay="100">
                <div class="card text-center box">
                    <img src="{% static 'img/python.jpeg' %}" width="100%" height="200px" alt="card-1"/>
                     <div class="card-footer py-2">
                        <a href="{% url 'pythonbasic:home' %}" class="text-uppercase bg-transparent text-black fw-bold fs-3">Python basics</a>
                     </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                <div class="card text-center box">
                    <img src="{% static 'img/java.jpg' %}" width="100%" height="200px" alt="card-1"/>
                    <div class="card-footer py-2">
                        <a href="{% url 'java:java-home' %}" class="text-uppercase fw-bold fs-3 text-black p-4">Java basics</a>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                <div class="card text-center box">
                    <img src="{% static 'img/android_1.jpeg' %}" width="100%" height="200px" alt="card-1"/>
                     <div class="card-footer py-2">
                        <a href="{% url 'android:android-home' %}" class="text-uppercase fw-bold fs-3 text-black p-4">Android basics</a>
                     </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Section posts -->
<section class="bg-light py-5">
    <div class="container-fluid">
        <div class="row gy-4 mt-1">
            <div class="col-12 col-md-12 col-lg-8 border-end border-3">
                <p class="text-center text-uppercase text-white py-2 post-titre">recent posts</p>
                {% if tag %}
                    <h2>Posts tagged with "{{ tag.name }}"</h2>
                {% endif %}
                {% if category %}
                    <h2>Category: {{ category.name }}</h2>
                {% endif %}
                {% for post in posts %}
                <div class="row gy-4 gx-4 mt-4">
                    <div class="col-12 col-md-12 col-lg-12">
                        <div class="row gy-4 py-2">
                            <div class="col-12 col-md-6 col-lg-6">
                                <div class="card shadow-4">
                                    <div class="card shadow">
                                        <img src="{% if post.image %}{{ post.image.url }}{% endif %}" alt="img"/>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-md-6 col-lg-6">
                                <h4>
                                    <a href="{{ post.get_absolute_url }}" class="text-decoration-none text-dark">
                                        {{ post.titre }}
                                    </a>
                                </h4>
                                 <p class="text-muted fst-italic">
                                     Tags:
                                     {% for tag in post.tags.all %}
                                        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                                            {{ tag.name }}
                                        </a>
                                        {% if not forloop.last %}, {% endif %}
                                     {% endfor %}
                                 </p>
                                <p class="text-secondary">Publié le {{ post.publish.date }} par {{ post.author }}</p>
                                <p>
                                    {{ post.body|safe|truncatewords_html:25 }}
                                </p>
                                <a href="{{ post.get_absolute_url }}"><button type="button" class="btn btn-dark mx-auto d-block">Voir l'article</button></a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
                <hr/>
                {% include "pagination.html" with page=posts %}
            </div>
            <div class="col-12 col-md-12 col-lg-4 ps-5">
                <p class="text-center text-uppercase text-white py-2 post-titre">a propos de moi</p>
                <div class="row gy-4 justify-content-md-center">
                    <div class="col-12">
                        <img src="{% static 'img/toph_1.png' %}" alt="photo de profil" class="rounded-circle mx-auto d-block" height="200px" width="200px"/>
                    </div>
                    <div class="col-12 col-md-12 mx-auto">
                        <p>
                            Salut, je suis Diarra Moustapha. Je suis diplomé en informatique et en ingeniérie passionné par
                            la programmation et la technologie.
                            Planète Python est l'endroit où je me passionne pour la programmation informatique.
                            Sur ce blog, je partage tout ce que j'apprends sur la programmation au fur et à mesure.
                        </p>
                        <a href=""><button type="button" class="btn btn-dark mx-auto d-block">En savoir plus</button></a>
                    </div>
                    <div class="col-12 col-md-12 mx-auto d-block">
                        <p class="text-center text-uppercase text-white py-2 post-titre">Informations legales</p>
                        <div class="col">
                            <p>
                                Planète Code est l'endroit où vous apprenez des compétences techniques et des compétences génerales pour devenir un meilleur programmeur.
                                Ce site appartient et est exploité par Diarra Moustapha.
                            </p>
                        </div>
                    </div>
                    <hr>
                </div>
            </div>
        </div>

        </div>
    </div>
</section>

{% endblock %}

blog/templates/blog/posts/pagination.html
<!--Pagination-->
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
    {% if page.has_previous %}
        <li class="page-item">
        <a class="page-link" href="?page={{ page.previous_page_number }}">Previous</a>
      </li>
    {% else %}
        <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="True">Previous</a>
      </li>
    {% endif %}
  
    {% if page.number|add:'-4' > 1 %}
        <li class="page-item"><a class="page-link" href="?page={{ page.number|add:'-5' }}">&hellip;</a></li>
    {% endif %}
  
    {% for i in page.paginator.page_range %}
        {% if page.number == i %}
          <li class="page-item active" aria-current="page">
          <span class="page-link">
            {{ i }}
            <span class="sr-only">(current)</span>
          </span>
        </li>
        {% elif i > page.number|add:'-5' and i < page.number|add:'5' %}
              <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
    {% endfor %}
  
    {% if page.paginator.num_pages > page.number|add:'4' %}
        <li class="page-item"><a class="page-link" href="?page={{ page.number|add:'5' }}">&hellip;</a></li>
    {% endif %}
  
    {% if page.has_next %}
        <li class="page-item ms-2">
        <a class="page-link" href="?page={{ page.next_page_number }}">Next</a>
      </li>
    {% else %}
        <li class="page-item disabled me-2">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="True">Next</a>
      </li>
    {% endif %}
    </ul>
  </nav>
  <!--end of Pagination-->
  

blog/templates/blog/posts/search.html
{% extends 'blog/base.html' %}
{% load static %}
{% load blog_tags %}

{% block content %}
<section class="bg-light py-5">
    <div class="container-fluid">
        <div class="row gy-4 mt-1">
            <div class="col-12 col-md-12 col-lg-8 border-end border-3 border-bottom">
                {% if query %}
                    <h1 class="text-dark text-capitalize">Articles contenant: {{ query }}</h1>

                    {% for post in results %}
                        <h3><a href="{{ post.get_absolute_url}}" class="text-center text-capitalize text-decoration-underline my-4 mx-auto d-block">{{ post.titre }}</a></h3>
                        <p class="text-secondary text-center mx-auto d-block">Publié le {{ post.publish.date }} par <a href="{% url 'blog:about' %}" class="text-decoration-underline">{{ post.author }}</a></p>
                        <a href="{{post.get_absolute_url}}"><img src="{% if post.image%}{{post.image.url}}{% endif %}" alt="img" width="600" height="400" class="my-4 mx-auto d-block"></a>
                        {{post.body|safe|truncatewords_html:25}}
                        <p>Post in <a href="{% url 'blog:post_list_by_category' post.category.slug %}" class="text-decoration-underline fst-italic">{{ post.category }}
                        </a> -Tagged {% for tag in post.tags.all %}<a href="{% url 'blog:post_list_by_tag' tag.slug%}" class="text-decoration-underline fst-italic">
                            {{ tag.name }} </a>{% if not forloop.last%}, {% endif %}{% endfor %}</p>
                        <hr/>
                    {% empty %}
                        <p>Désolé, Nous n'avons pas trouvé de posts contenant:<strong>{{query}}</strong>.</p>
                    {% endfor %}
                    <p><a href="{% url 'blog:post_search' %}" class="btn btn-primary">Search again</a>
                {% else %}
                    <h1>Search for posts</h1>
                    <form method="get">
                        {{ form.as_p }}
                        <input type="submit" name="" value="Search">
                    </form>
                {% endif %}
                {% include "pagination.html" with page=posts %}
            </div>
            <div class="col-12 col-md-12 col-lg-4">
                <p class="text-center text-uppercase text-white py-2 post-titre">a propos de moi</p>
                <div class="row gy-4 justify-content-md-center">
                    <div class="col-12">
                        <img src="{% static 'img/toph_1.png' %}" alt="photo de profil" class="rounded-circle mx-auto d-block" height="200px" width="200px"/>
                    </div>
                    <div class="col-12 col-md-12 mx-auto">
                        <p>
                            Salut, je suis Diarra Moustapha. Je suis diplomé en informatique et en ingeniérie passionné par
                            la programmation et la technologie.
                            Planète Python est l'endroit où je me passionne pour la programmation informatique.
                            Sur ce blog, je partage tout ce que j'apprends sur la programmation au fur et à mesure.
                        </p>
                        <a href=""><button type="button" class="btn btn-dark mx-auto d-block">En savoir plus</button></a>
                    </div>
                    <div class="col-12 col-md-12 mx-auto d-block">
                        <p class="text-center text-uppercase text-white py-2 post-titre">Informations legales</p>
                        <div class="col p-4">
                            <p>
                                Planète Code est l'endroit où vous apprenez des compétences techniques et des compétences génerales pour devenir un meilleur programmeur.
                                Ce site appartient et est exploité par Diarra Moustapha.
                            </p>
                        </div>
                    </div>
                    <hr>
                </div>
            </div>
        </div>


        </div>
    </div>
</section>

{% endblock %}

blog/templates/blog/posts/subscribe_email.html
{% extends 'blog/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<section class='subcribe'>
    <div class="container">
        <div class="row gy-4 py-4" >
            <div class="col-md-4 offset-md-4">
                <div class="card shadow">
                    <div class="card-body">
                        <h4>Subscribe by email</h4>
                        <hr/>
                        <form method="post">
                        {{ form |crispy }}
                        <input type="submit" value="Subscribe" class="btn btn-primary w-100 mt-3">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>    
</section>

{% endblock %}