blog/urls.py
from django.urls import path

from blog import views
from blog.feeds import LatestPostsFeed

app_name = 'blog'
urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list_by_category, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name="post_share"),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
    path('about/', views.about, name='about'),
    path('about_site/', views.about_site, name='about_site'),
    path('book_list/', views.BookListView.as_view(), name='book_list'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('<slug:category_slug>/', views.post_list_by_category, name='post_list_by_category'),
    path('<int:pk>/download_image/', views.download_idea_picture, name='download_book_image'),
    path('comment/reply/', views.reply, name='reply'),
]

code_planete/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('java/', include('java.urls', namespace='java')),
    path('android/', include('android.urls', namespace='android')),
    path('pythonbasic/', include('pythonbasic.urls', namespace='pythonbasic')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:post_list_by_category', args=[self.slug])


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='posts')
    titre = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = RichTextUploadingField(blank=True, null=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    image = models.ImageField(upload_to='img/', blank=True)
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish', )

    def __str__(self):
        return self.titre

    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.publish.year, self.publish.month,
                                                 self.publish.day, self.slug])

    def get_comments(self):
        return self.comments.filter(parent=None).filter(active=True)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    parent = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True)
    body = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

    def get_comments(self):
        return Comment.objects.filter(parent=self).filter(active=True)


class Book(models.Model):
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    image = models.ImageField(upload_to='img/', blank=True, null=True)
    pdf = models.FileField(upload_to='pdf_file/', blank=True, max_length=250)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return f'{self.title}  - {self.author}'


class Subscribe(models.Model):
    email = models.EmailField()

    def __str__(self):
        return f'{self.email}'

blog/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms

from blog.models import Comment, Subscribe


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25, widget=forms.TextInput(attrs={'class': 'name'}), label='name')
    email = forms.EmailField(label='Email')
    to = forms.EmailField(label='Email')
    comments = forms.CharField(required=False,
                              widget=forms.Textarea, label='Comment')


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')
        widgets = {
            'name':forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Votre nom'}),
            'email':forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Votre email'}),
            'body':forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Commentaire ...'}),
        }


class SearchForm(forms.Form):
    query = forms.CharField()


class SubscribeForm(forms.ModelForm):
    class Meta:
        model = Subscribe
        fields = '__all__'

blog/views.py
import os.path
import datetime
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.core.mail import send_mail
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count, Q
from django.http import FileResponse, HttpResponseNotFound
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.text import slugify
from django.views.generic import ListView
from blog.forms import EmailPostForm, CommentForm, SearchForm, SubscribeForm
from blog.models import Post, Comment, Category, Book
from taggit.models import Tag
from blog.documents import PostDocument, CategoryDocument


def post_list(request, tag_slug=None, category_slug=None):
    now = datetime.datetime.now
    object_list = Post.published.all()
    tag = None
    category = None
    categories = Category.objects.all()

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        object_list = object_list.filter(category__in=[category])
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 6)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first in each page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver the first page
        posts = paginator.page(paginator.num_pages)
    context = {
        'posts': posts,
        'page': page,
        'tag': tag,
        'category': category,
        'categories': categories,
        'now': now,
    }
    return render(request, 'blog/posts/list.html', context=context)


def post_list_by_category(request, category_slug=None, tag_slug=None):
    now = datetime.datetime.now
    object_list = Post.published.all()
    categories = Category.objects.all()
    category = None
    tag = None
    author = None
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        object_list = object_list.filter(category__in=[category])

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 6)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    context = {
        'categories': categories,
        'category': category,
        'posts': posts,
        'page': page,
        'tag': tag,
        'author': author,
        'now': now,
    }
    return render(request, 'blog/posts/post_list_category.html', context=context)


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published', publish__year=year,
                             publish__month=month, publish__day=day)
    categories = Category.objects.all()
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            return redirect(post.get_absolute_url()+'#'+str(new_comment.id))
    else:
        comment_form = CommentForm()
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:2]
    context = {
        'post': post,
        'comments': comments,
        'comment_form': comment_form,
        'similar_posts': similar_posts,
        'categories': categories,
    }
    return render(request, 'blog/posts/detail.html', context=context)


def reply(request):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            post_id = request.POST.get('post_id')
            parent_id = request.POST.get('parent')
            post_url = request.POST.get('post_url')

            reply = form.save(commit=False)
            reply.post = Post(id=post_id)
            reply.parent = Comment(id=parent_id)
            reply.save()
            return redirect(post_url+'#'+str(reply.id))
    return redirect('/')


def post_share(request, post_id):
    # Recuperer un post par son identifiant
    post = get_object_or_404(Post, id=post_id, status='published')
    categories = Category.objects.all()
    sent = False
    if request.method == 'POST':
        # Formulaire a ete soumis
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # formulaire est valide
            cd = form.cleaned_data
            # email envoyé
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommands you read"\
                        f"{post.titre}"
            message = f"Read {post.titre} at {post_url}\n\n"\
                    f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'diarra.msa1@gmail.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    # La liste des posts similaires
    context = {
        'post': post,
        'form': form,
        'sent': sent,
        'categories': categories,
    }
    return render(request, 'blog/posts/share.html', context=context)


def post_search(request, tag_slug=None):
    categories = Category.objects.all()
    object_list = Post.published.all()
    form = SearchForm()
    query = request.GET.get('query')
    tag = None
    results = []
    paginator = Paginator(object_list, 6)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    if query:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.published.filter(Q(titre__icontains=query) | Q(body__icontains=query))
    context = {
        'form': form,
        'query': query,
        'results': results,
        'categories': categories,
        'tag': tag,
        'object_list': object_list,
        'posts': posts,
        'page': page,
    }
    return render(request, 'blog/posts/search.html', context=context)


def about(request):
    categories = Category.objects.all()
    context = {
        'categories': categories
    }
    return render(request, 'blog/posts/about.html', context=context)


def about_site(request):
    categories = Category.objects.all()
    context = {
        'categories': categories
    }
    return render(request, 'blog/posts/about_site.html', context=context)


class BookListView(ListView):
    
    model = Book
    template_name = 'blog/posts/book_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categories = Category.objects.all()
        context['categories'] = categories
        return context


def download_idea_picture(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if book.pdf:
        filename, extension = os.path.splitext(book.pdf.file.name)
        extension = extension[1:]
        response = FileResponse(
            book.pdf.file, content_type=f"image/{extension}"
        )
        slug = slugify(book.title)[:100]
        response["Content-Disposition"] = (
            "attachement; filename="
            f"{slug}.{extension}"
        )
    else:
        response = HttpResponseNotFound(
            content="file invalide"
        )
    return response


def subscribe(request):
    my_form = SubscribeForm()
    if request.method == 'POST':
        my_form = SubscribeForm(data=request.POST or None)
        if my_form.is_valid():
            cd = my_form.cleaned_data
            my_form.save()
            return redirect('blog:book_list')
        else:
            my_form = SubscribeForm()
    else:
        my_form = SubscribeForm()
    return render(request, 'blog/posts/subscribe_email.html', {'my_form': my_form})

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
{% load crispy_forms_tags %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Google font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <!-- Aos js -->
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <link href="https://fonts.googleapis.com/css2?family=Libre+Franklin:wght@100&display=swap" rel="stylesheet">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
    <!-- Fonts Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.2.0/fonts/remixicon.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/7.4.1/swiper-bundle.min.css" integrity="sha512-kftIhGv/k/oRHmfDRDEb1MxlaWlW4tiz21rx0yNC2zUWM2n4nxRtX1z3Ijmu54he3Yf9sBX4skJaCe3LTJV1rQ=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet"
      href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.4.0/styles/default.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.4.0/highlight.min.js"></script>
    {% load static %}
    <link href="{% static 'css/style.css' %}" rel="stylesheet"/>
    <title>Code planète</title>
</head>
<body>
    <div class="container">
           <!-- Navbar content -->
        <section id="navbar-content">
            <div class="container-fluid">
                <nav class="navbar navbar-expand-lg navbar-light fixed-top text-light navbar-header">
                    <div class="container-fluid">
                        <a class="navbar-brand ms-5 fw-bold fs-1 text-white text-center titre" href="{% url 'blog:post_list'%}">
                            Planète Code
                        </a>
                        <button class="navbar-toggler bg-white " type="button" data-bs-toggle="collapse" data-bs-target="#navbarBlog" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarBlog">
                            <ul class="navbar-nav ms-auto mb-2 me-5 mb-lg-0 text-center text-uppercase text-white">
                                <li class="nav-item">
                                    <a class="nav-link active text-white" aria-current="page" href="{% url 'blog:post_list' %}">Home</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a id="propos" class="nav-link text-white dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">A propos</a>
                                    <ul class="dropdown-menu" aria-labelledby="propos">
                                         <li><a class="dropdown-item mb-3" href="{% url 'blog:about_site' %}">À propos de Planète Code</a></li>
                                         <li><a class="dropdown-item mb-3" href="{% url 'blog:about' %}">À De Moustapha D</a></li>
                                    </ul>
                                </li>
                                <li class="nav-item dropdown">
                                    <a id="sujet" class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Sujets</a>
                                     <ul class="dropdown-menu" aria-labelledby="sujet">
                                         {% for c in categories %}
                                         <li><a class="dropdown-item mb-3" href="{{ c.get_absolute_url }}">{{ c.name }}</a></li>
                                         {% endfor %}
                                    </ul>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" href="{% url 'blog:book_list' %}">Livres Electroniques</a>
                                </li>
                            </ul>
                            <form class="d-flex justify-content-md-center me-5" method="get" action="{% url 'blog:post_search' %}">
                                {% csrf_token %}
                                <input class="form-control me-2" type="search" name="query" placeholder="Search" aria-label="Search">
                                <button class="btn btn-outline-success text-white text-uppercase border-white" type="submit">Search</button>
                            </form>
                        </div>
                    </div>
                </nav>
            </div>
        </section>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
        <!-- section footer -->
       <footer id="footer" class="footer mt-4">
            <div class="footer-top">
              <div class="container">
                <div class="row gy-4">
                  <div class="col-lg-5 col-md-12 footer-info">
                    <a href="{% url 'blog:post_list' %}" class="logo d-flex align-items-center">
                      <span class="fst-italic">Planète Code</span>
                    </a>
                    <p class="mt-5 fst-italic">
                        Planète Code est l'endroit où vous apprenez des
                        competences techniques et des competences génerales pou devenir un meilleur programmeur.
                        Ce site appartient et est exploité par Diarra Moustapha.
                    </p>
                    <div class="social-links mt-3">
                      <a href="#" class="quora"><i class="bi bi-quora"></i></a>
                      <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                      <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
                    </div>
                  </div>

                  <div class="col-lg-2 col-6 footer-links">
                    <h4>Liens Utils</h4>
                    <ul>
                      <li><i class="bi bi-chevron-right"></i> <a href="#">Home</a></li>
                      <li><i class="bi bi-chevron-right"></i> <a href="#">A props de moi</a></li>
                      <li><i class="bi bi-chevron-right"></i> <a href="#">Services</a></li>
                      <li><i class="bi bi-chevron-right"></i> <a href="#">Terms of service</a></li>
                      <li><i class="bi bi-chevron-right"></i> <a href="#">Privacy policy</a></li>
                    </ul>
                  </div>

                  <div class="col-lg-2 col-6 footer-links">
                    <h4>Mes Services</h4>
                    <ul>
                      <li><i class="bi bi-chevron-right"></i> <a href="#">Web Design</a></li>
                      <li><i class="bi bi-chevron-right"></i> <a href="#">Développeur Web & Android</a></li>
                      <li><i class="bi bi-chevron-right"></i> <a href="#">Graphic Design</a></li>
                    </ul>
                  </div>

                  <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
                    <h4>Contactez Moi</h4>
                    <p>
                      Imama Shamilya 70 <br>
                      Makhatchkala, 367030<br>
                      Russie <br><br>
                      <strong>Phone:</strong> +7 989 459 10 79<br>
                      <strong>Email:</strong><a href="mailto:diarra.msa@gmail.com"> diarra.msa@gmail.com</a><br>
                    </p>

                  </div>

                </div>
              </div>
            </div>

            <div class="container">
              <div class="copyright">
                &copy; {% now "Y" %} Copyright <strong><span>DinoDev</span></strong>. All Rights Reserved
              </div>
              <div class="credits">
                Designed by <a href="{% url 'blog:about' %}">Diarra Moustapha</a>
              </div>
            </div>
    </footer><!-- End Footer -->
        <!-- END FOOTER -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
     <script>hljs.highlightAll();</script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/7.4.1/swiper-bundle.min.js"
             integrity="sha512-pY1t/ADgTwbfGbw0+mRGd33EroA5YgRUWhQNFpPIAdBzyoSb38FsFrf4wBTcS3GFPdTfgtpRrbGCkdl2C2OXYA=="
             crossorigin="anonymous" referrerpolicy="no-referrer">
     </script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha512-Zq2BOxyhvnRFXu0+WE6ojpZLOU2jdnqbrM1hmVdGzyeCa1DgM3X5Q4A/Is9xA1IkbUeDd7755dNNI/PzSf2Pew=="
             crossorigin="anonymous" referrerpolicy="no-referrer">
     </script>
     <script src="https://cdn.jsdelivr.net/npm/glightbox@3.1.0/dist/js/glightbox.min.js"></script>
    <script>
      AOS.init();
    </script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>