android/urls.py
from django.urls import path
from android import views


app_name = 'android'

urlpatterns = [
    path('', views.AndroidListView.as_view(), name='android-home'),
    path('<int:pk>/', views.android_detail, name='android-detail'),
   #path('tag/<slug:tag_slug>/', views.article_list_by_category, name='article_list_by_tag'),
    path('comment/reply/', views.reply_page, name='reply'),
]

blog/urls.py
from django.urls import path

from blog import views
from blog.feeds import LatestPostsFeed

app_name = 'blog'
urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list_by_category, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name="post_share"),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
    path('about/', views.about, name='about'),
    path('about_site/', views.about_site, name='about_site'),
    path('book_list/', views.BookListView.as_view(), name='book_list'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('<slug:category_slug>/', views.post_list_by_category, name='post_list_by_category'),
    path('<int:pk>/download_image/', views.download_idea_picture, name='download_book_image'),
    path('comment/reply/', views.reply, name='reply'),
]

code_planete/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('java/', include('java.urls', namespace='java')),
    path('android/', include('android.urls', namespace='android')),
    path('pythonbasic/', include('pythonbasic.urls', namespace='pythonbasic')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

android/models.py
from statistics import mode
from django.contrib.auth.models import User
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from ckeditor.fields import RichTextField
from taggit.managers import TaggableManager
from blog.models import Category

# Create your models here.
from django.urls import reverse
from django.utils import timezone


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class AndroidArticle(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    titre = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='android_auteur')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='categories', null=True)
    body = RichTextUploadingField()
    publish = models.DateTimeField(default=timezone.now)
    image = models.ImageField(upload_to='img/', blank=True)
    status = models.CharField(max_length=255, choices=STATUS_CHOICES, default='draft')
    published = PublishedManager()
    tags = TaggableManager()

    def __str__(self):
        return self.titre

    def get_absolute_url(self):
        return reverse('android:android-detail', args=[str(self.id)])

    def get_comments(self):
        return self.comments.filter(parent=None).filter(active=True)



class CommentArticle(models.Model):
    article = models.ForeignKey(AndroidArticle, on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=80)
    email = models.EmailField(blank=True, null=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True)
    body = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Comment by {self.author} on {self.article.titre}'

    def get_comments(self):
        return CommentArticle.objects.filter(parent=self).filter(active=True)

android/forms.py
from django import forms
from android.models import CommentArticle


class CommentForm(forms.ModelForm):
    class Meta:
        model = CommentArticle
        fields = ('author', 'email', 'body')
        widgets = {
            'author': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nom:'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Nom:'}),
            'body': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Commentaire ....'})
        }

    

android/views.py
import datetime
from re import T
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone
from django.views.generic import ListView
from django.db.models import Count
from .models import AndroidArticle, CommentArticle
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from blog.models import Category
from .forms import CommentForm
from taggit.models import Tag


class AndroidListView(ListView):
    model = AndroidArticle
    paginate_by = 6
    template_name = "android/android_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        context['android_articles'] = AndroidArticle.published.all()
        context['categories'] = Category.objects.all()
        return context



def android_detail(request, pk):
    article = get_object_or_404(AndroidArticle, pk=pk)
    categories = Category.objects.all()
    
    # Liste de commentaire active pour chaque article
    comments = article.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Creer un objet CommentArticle mais ne sauvegardez pas
            new_comment = comment_form.save(commit=False)
            # Faire correspondre l'article correspond au commentaie
            new_comment.article = article
            # Sauvegarder le commentaire de cet article
            new_comment.save()
            # redirectiion sur la meme page
            return redirect(article.get_absolute_url()+'#'+str(new_comment.id))
    else:
        comment_form = CommentForm()

    post_tags_ids = article.tags.values_list('id', flat=True)
    similar_articles = AndroidArticle.published.filter(tags__in=post_tags_ids).exclude(id=article.id)
    similar_articles = similar_articles.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:2]
    context = {
        'article': article,
        'comments': comments,
        'comment_form': comment_form,
        'categories': categories,
        'similar_articles': similar_articles,
    }
    return render(request, 'android/android_detail.html', context)


def reply_page(request):
    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            article_id = request.POST.get('article_id')
            parent_id = request.POST.get('parent')
            article_url = request.POST.get('article_url')

            reply = form.save(commit=False)
            reply.article = AndroidArticle(id=article_id)
            reply.parent = CommentArticle(id=parent_id)
            reply.save()

            return redirect(article_url+'#'+str(reply.id))

    return redirect("/")

android/templates/android/android_detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% load blog_tags %}
{% load crispy_forms_tags %}

{% block content %}

<!-- Section posts -->
<section class="py-5">
    <div class="container-fluid">
        <div class="row gy-4 mt-md-0 mt-5">
            <div class="col-12 col-md-12 col-lg-8 border-end border-warning border-3">
                <h2 class="text-center">{{ article.titre }}</h2>
                <p class="text-secondary text-center">Publié le {{ article.publish.date }} par {{ article.author }}</p>
                <img src="{% if article.image %}{{ article.image.url }}{% endif %}" class="mx-auto d-block" height="260px" width="100%">

                <p>
                    {{ article.body|safe }}
    
                </p>
                <p>
                    <strong>Tags:</strong>
                    {% for tag in article.tags.all %}
                        <a href="{% url 'blog:post_list_by_tag' tag.slug %}" class="link-light text-decoration-none badge bg-secondary">
                            {{ tag.name }}
                        </a>
                    {% endfor %}
                </p>
                <hr/>
                <div class="row mt-4 g-3 justify-content-center">
                    <div class="col col-md-3 col-lg-3">
                       <img src="{% static 'img/toph_4.png' %}" class="rounded-circle bg-secondary mx-auto d-block" alt="img" height="140px" width="140px">
                    </div>
                    <div class="col-12 col-md-9 col-lg-9 ps-4">
                        <h3 class="text-dark fw-bold fs-2 text-center text-md-start text-lg-start">Diarra Moustapha</h3>
                        <p>
                            Je suis le visage derrière Planète Code. J'ai appris mon premier langage de programmation en 2018.
                            Depuis, j'apprends la programmation et je me plonge dans la technologie.
                            Sur ce site, je partage tout ce que j'ai appris sur la programmation informatique.
                        </p>
                    </div>
                </div>
                <hr/>
                <p>
                    <a href="" class="btn btn-primary">Partager cet article</a>
                </p>
                {% with comments.count as total_comments %}
                    <h2>
                        {{ total_comments }} comment{{ total_comments|pluralize }}
                    </h2>
                {% endwith %}
                
                {% if not article.comments.all %}
                    No comments yet
                
                {% else %}
                    {% for comment in article.get_comments %}
                        {% include 'android/comment.html' with comment=comment %}
                    {% endfor %}
                {% endif %}
                <br />
                <hr />
                <h3 class="text-center">Laisser un commentaire</h3>
                <form method="POST" action="" class="row form-group mt-3">
                    {% csrf_token %}
                    <div class="col-6">
                        {{ comment_form.author }}
                    </div>
                    <div class="col-6">{{ comment_form.email }}</div>
                    <div class="col-12 mt-2">{{ comment_form.body }}</div>
                    <a><button type="submit" class="btn btn-secondary mt-2">Comment</button></a>
                </form>
                <div class="row gy-4 mt-4">
                    <h2>Posts similaires : </h2>
                    {% for article in similar_articles %}
                        <div class="col-12 col-sm-12 col-md-6 col-lg-6">
                            <img src="{% if article.image %}{{ article.image.url }}{% endif %} " class="w-100 mt-sm-4" alt="..."/>
                            <p class="mt-4 text-center">
                                <a href="{{ article.get_absolute_url }}" class="text-decoration-none fw-bolder fs-5 text-dark">{{ article.titre }}</a>
                            </p>
                            <p>
                                {{ article.body|safe|truncatewords_html:25 }}
                            </p>
                            <p class="text-center"><a href="{{ article.get_absolute_url }}" class="btn btn-secondary text-decoration-none text-center text-uppercase mb-sm-4">Continue...</a></p>
                        </div>
                    {% empty %}
                        <p>Il n'y a pas de posts similar.</p>
                    {% endfor %}
                </div>
            </div>
            <div class="col-12 col-md-12 col-lg-4 ps-5">
                <p class="text-center text-uppercase text-white py-2 post-titre">À propos de moi</p>
                <div class="row gy-4 justify-content-md-center">
                    <div class="col-12 justify-content-md-center">
                        <img src="{% static 'img/toph_1.png' %}" alt="photo de profil" class="rounded-circle mx-auto d-block" height="200px" width="200px"/>
                    </div>
                    <div class="col-12 col-md-12 mx-auto">
                        <p>
                            Salut, je suis Diarra Moustapha. Je suis diplomé en informatique et en ingeniérie passionné par
                            la programmation et la technologie.
                            Planète Python est l'endroit où je me passionne pour la programmation informatique.
                            Sur ce blog, je partage tout ce que j'apprends sur la programmation au fur et à mesure.
                        </p>
                        <a href=""><button type="button" class="btn btn-dark mx-auto d-block">En savoir plus</button></a>
                        <hr>
                    </div>
                    <div class="col-12 col-md-12 mx-auto d-block mt-4">
                        <p class="text-center text-uppercase text-white py-2 post-titre">Informations legales</p>
                        <div class="col">
                            <p>
                                Planète Code est l'endroit où vous apprenez des competences techniques et des competences generales pou devenir un meilleur programmeur.
                                Ce site appartient et exploite par Diarra Moustapha.
                            </p>
                            <hr>
                        </div>
                    </div>

                </div>
            </div>
        </div>

        </div>
    </div>
</section>

{% endblock %}

android/templates/android/android_list.html
{% extends 'blog/base.html' %}
{% load static %}
{% load blog_tags %}

{% block content %}

<!-- Section posts -->
<section class="bg-light py-5">
    <div class="container-fluid">
        <div class="row gy-4 mt-1">
            <div class="col-12 col-md-12 col-lg-8 border-end border-3">
                <p class="text-center text-uppercase text-white py-2 post-titre">Les bases de Android</p>
                {% for article in android_articles %}
                <div class="row gy-4 gx-4 mt-4">
                    <div class="col-12 col-md-12 col-lg-12">
                        <div class="row gy-4 py-2">
                            <div class="col-12 col-md-6 col-lg-6">
                                <div class="card shadow-4">
                                    <div class="card shadow">
                                        <img src="{% if article.image %}{{ article.image.url }}{% endif %}" alt="img"/>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-md-6 col-lg-6">
                                <h4>
                                    <a href="{{ article.get_absolute_url }}" class="text-decoration-none text-dark">
                                        {{ article.titre }}
                                    </a>
                                </h4>
                                 <p class="text-muted fst-italic">
                                     Tags:
                                     {% for tag in article.tags.all %}
                                        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                                            {{ tag.name }}
                                        </a>
                                        {% if not forloop.last %}, {% endif %}
                                     {% endfor %}
                                 </p>
                                <p class="text-secondary">Publié le {{ article.publish.date }} par {{ article.author }}</p>
                                <p>
                                    {{ article.body|safe|truncatewords_html:25 }}
                                </p>
                                <a href="{{ article.get_absolute_url }}"><button type="button" class="btn btn-dark mx-auto d-block">Voir l'article</button></a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
                <hr/>
                {% include "android/pagination.html" with page=page_obj %}
            </div>
            <div class="col-12 col-md-12 col-lg-4 ps-5">
                <p class="text-center text-uppercase text-white py-2 post-titre">a propos de moi</p>
                <div class="row gy-4 justify-content-md-center">
                    <div class="col-12">
                        <img src="{% static 'img/toph_1.png' %}" alt="photo de profil" class="rounded-circle mx-auto d-block" height="200px" width="200px"/>
                    </div>
                    <div class="col-12 col-md-12 mx-auto">
                        <p>
                            Salut, je suis Diarra Moustapha. Je suis diplomé en informatique et en ingeniérie passionné par
                            la programmation et la technologie.
                            Planète Python est l'endroit où je me passionne pour la programmation informatique.
                            Sur ce blog, je partage tout ce que j'apprends sur la programmation au fur et à mesure.
                        </p>
                        <a href=""><button type="button" class="btn btn-dark mx-auto d-block">En savoir plus</button></a>
                    </div>
                    <div class="col-12 col-md-12 mx-auto d-block">
                        <p class="text-center text-uppercase text-white py-2 post-titre">Informations legales</p>
                        <div class="col">
                            <p>
                                Planète Code est l'endroit où vous apprenez des compétences techniques et des compétences génerales pour devenir un meilleur programmeur.
                                Ce site appartient et est exploité par Diarra Moustapha.
                            </p>
                        </div>
                    </div>
                    <hr>
                </div>
            </div>
        </div>

        </div>
    </div>
</section>

{% endblock %}

android/templates/android/comment.html
{% load crispy_forms_tags %}
<div class="border-0 border-start border-2 border-info ps-2" id="{{comment.id}}">
    <div class="mt-3">
        <strong>{{comment.author}}</strong> 
        {% if  comment.parent.author%} to <strong>{{comment.parent.author}}</strong>{% endif %}
        <small class="text-muted">On {{ comment.created.date }}</small>
    </div>
    <div class="border p-2 rounded">
        <p>{{ comment.body|safe }}</p>
        <button class="btn btn-primary btn-sm" onclick="handleReply({{comment.id}})">Reply</button>
    
        <div id="reply-form-container-{{comment.id}}" style="display:none">
        
            <form method="POST" action="{% url 'android:reply' %}" class="mt-3">
                {% csrf_token %}
                <input type="hidden" name="article_id" value="{{article.id}}">
                <input type="hidden" name="parent" value="{{comment.id}}">
                <input type="hidden" name="article_url" value="{{ article.get_absolute_url }}">
                {{comment_form|crispy }}
                <div class="mt-2">
                    <button type="button" onclick="handleCancel({{comment.id}})" class="btn btn-light border btn-sm">Cancel</button>
                    <button type="submit" class="btn btn-primary btn-sm">Submit</button>
                </div>
            </form>
        </div>
    </div>
    {% for comment in comment.get_comments %}
        {% include 'android/comment.html' with comment=comment %}
    {% endfor %}
</div>

android/templates/android/list_by_tag.html
{% extends 'blog/base.html' %}
{% load static %}
{% load blog_tags %}

{% block content %}
<section class="bg-light py-5">
    <div class="container-fluid">
        <div class="row gy-4 mt-1">
            <div class="col-12 col-md-12 col-lg-8 border-end border-3">
                <p class="text-center text-uppercase text-white py-2 post-titre">recent posts</p>
                {% if tag %}
                    <h2>Posts tagged with "{{ tag.name }}"</h2>
                {% endif %}
                {% if category %}
                    <h2>Category: {{ category.name }}</h2>
                {% endif %}
                {% for post in posts %}
                <div class="row gy-4 gx-4 mt-4">
                    <div class="col-12 col-md-12 col-lg-12">
                        <div class="row gy-4 py-2">
                            <div class="col-12 col-md-6 col-lg-6">
                                <div class="card shadow-4">
                                    <div class="card shadow">
                                        <img src="{% if post.image %}{{ post.image.url }}{% endif %}" alt="img"/>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-md-6 col-lg-6">
                                <h4>
                                    <a href="{{ post.get_absolute_url }}" class="text-decoration-none text-dark">
                                        {{ post.titre }}
                                    </a>
                                </h4>
                                 <p class="text-muted fst-italic">
                                     Tags:
                                     {% for tag in post.tags.all %}
                                        <a href="{% url 'android:article_list_by_tag' tag.slug %}">
                                            {{ tag.name }}
                                        </a>
                                        {% if not forloop.last %}, {% endif %}
                                     {% endfor %}
                                 </p>
                                <p class="text-secondary">Publié le {{ post.publish.date }} par {{ post.author }}</p>
                                <p>
                                    {{ post.body|safe|truncatewords_html:25 }}
                                </p>
                                <a href="{{ post.get_absolute_url }}"><button type="button" class="btn btn-dark mx-auto d-block">Voir l'article</button></a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
                <hr/>
                {% include "android/pagination.html" with page=posts %}
            </div>
            <div class="col-12 col-md-12 col-lg-4 ps-5 ">
                <p class="text-center text-uppercase text-white py-2 post-titre">a propos de moi</p>
                <div class="row gy-4 justify-content-md-center">
                    <div class="col-12">
                        <img src="{% static 'img/toph_1.png' %}" alt="photo de profil" class="rounded-circle mx-auto d-block" height="200px" width="200px"/>
                    </div>
                    <div class="col-12 col-md-12 mx-auto">
                        <p>
                            Salut, je suis Diarra Moustapha. Je suis diplomé en informatique et en ingeniérie passionné par
                            la programmation et la technologie.
                            Planète Python est l'endroit où je me passionne pour la programmation informatique.
                            Sur ce blog, je partage tout ce que j'apprends sur la programmation au fur et à mesure.
                        </p>
                        <a href=""><button type="button" class="btn btn-dark mx-auto d-block">En savoir plus</button></a>
                    </div>
                    <div class="col-12 col-md-12 mx-auto d-block">
                        <p class="text-center text-uppercase text-white py-2 post-titre">Informations legales</p>
                        <div class="col">
                            <p>
                                Planète Code est l'endroit où vous apprenez des compétences techniques et des compétences génerales pour devenir un meilleur programmeur.
                                Ce site appartient et est exploité par Diarra Moustapha.
                            </p>
                        </div>
                    </div>
                    <hr>
                </div>
            </div>
        </div>

        </div>
    </div>
</section>
{% endblock %}

android/templates/android/pagination.html
<!--Pagination-->
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
  {% if page.has_previous %}
      <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">Previous</a>
    </li>
  {% else %}
      <li class="page-item disabled">
      <a class="page-link" href="#" tabindex="-1" aria-disabled="True">Previous</a>
    </li>
  {% endif %}

  {% if page.number|add:'-4' > 1 %}
      <li class="page-item"><a class="page-link" href="?page={{ page.number|add:'-5' }}">&hellip;</a></li>
  {% endif %}

  {% for i in page.paginator.page_range %}
      {% if page.number == i %}
        <li class="page-item active" aria-current="page">
        <span class="page-link">
          {{ i }}
          <span class="sr-only">(current)</span>
        </span>
      </li>
      {% elif i > page.number|add:'-5' and i < page.number|add:'5' %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
  {% endfor %}

  {% if page.paginator.num_pages > page.number|add:'4' %}
      <li class="page-item"><a class="page-link" href="?page={{ page.number|add:'5' }}">&hellip;</a></li>
  {% endif %}

  {% if page.has_next %}
      <li class="page-item ms-2">
      <a class="page-link" href="?page={{ page.next_page_number }}">Next</a>
    </li>
  {% else %}
      <li class="page-item disabled me-2">
      <a class="page-link" href="#" tabindex="-1" aria-disabled="True">Next</a>
    </li>
  {% endif %}
  </ul>
</nav>
<!--end of Pagination-->